name: Notify Discord on Push
on:
  push:
    branches: [ main ]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          commits=$(jq -r '.commits[] | "- " + .message + " (" + .url + ")"' $GITHUB_EVENT_PATH | paste -sd '\n' -)
          repo=${GITHUB_REPOSITORY}
          actor=${GITHUB_ACTOR}
          payload=$(jq -n --arg repo "$repo" --arg actor "$actor" --arg commits "$commits" \
            '{username:"GitHub Bot", embeds:[{title:"Push to \($repo)", description:"**\($actor)** pushed:\n\($commits)", color:65280}]}')
          curl -H "Content-Type: application/json" \
               -d "$payload" \
               ${{ secrets.DISCORD_WEBHOOK }}
